services:
  - type: web
    name: bgremove-service
    env: python
    plan: free            # bump to starter-1GB if you hit OOM (see note 3)
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers
